In [2]:
import numpy as np
import pandas as pd

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df=pd.read_csv('covid_toy.csv')

In [14]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [16]:
df.isnull().sum()


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [24]:
X_train

age  gender  fever   cough       city
31   83    Male  103.0    Mild    Kolkata
5    84  Female    NaN    Mild  Bangalore
93   27    Male  100.0    Mild    Kolkata
59    6  Female  104.0    Mild    Kolkata
81   65    Male   99.0    Mild      Delhi
..  ...     ...    ...     ...        ...
18   64  Female   98.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
55   81  Female  101.0    Mild     Mumbai
25   23    Male    NaN    Mild     Mumbai
52   47  Female  100.0  Strong  Bangalore

[80 rows x 5 columns]

# Encoding Without using the columntransformer

In [33]:
#adding simple imputer to fever column
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [61]:
#ordinal encodinf->cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough =oe.fit_transform(X_train[['cough']])
#also the test data
X_test_cough =oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [63]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],

In [65]:
#OneHotencoding -> gender,city
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])

#also the test data
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape


(80, 4)

In [67]:
X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],


In [69]:
#extracting age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [71]:
X_train_age

array([[83],
       [84],
       [27],
       [ 6],
       [65],
       [25],
       [81],
       [72],
       [ 5],
       [83],
       [12],
       [55],
       [14],
       [16],
       [60],
       [65],
       [51],
       [23],
       [10],
       [20],
       [19],
       [75],
       [33],
       [ 5],
       [66],
       [50],
       [10],
       [82],
       [19],
       [80],
       [24],
       [71],
       [51],
       [17],
       [46],
       [42],
       [22],
       [64],
       [38],
       [74],
       [48],
       [73],
       [70],
       [ 8],
       [19],
       [69],
       [65],
       [56],
       [71],
       [59],
       [51],
       [73],
       [19],
       [20],
       [49],
       [26],
       [31],
       [11],
       [49],
       [42],
       [80],
       [ 5],
       [47],
       [18],
       [38],
       [42],
       [54],
       [27],
       [27],
       [75],
       [79],
       [64],
       [13],
       [34],
       [60],
       [64],
       [15],

In [73]:

X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [75]:
X_train_transformed

array([[ 83.  , 103.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 84.  , 100.75,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 27.  , 100.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [  6.  , 104.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 65.  ,  99.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ],
       [ 25.  ,  99.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ],
       [ 81.  ,  98.  ,   0.  ,   0.  ,   0.  ,   1.  ,   1.  ],
       [ 72.  ,  99.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  5.  , 100.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 83.  , 101.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 12.  , 104.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 55.  , 100.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 14.  , 101.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ],
       [ 16.  , 103.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 60.  , 103.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ],
       [ 65.  ,  99.  ,  

# Encode with ColumnTransformer

In [88]:
from sklearn.compose import ColumnTransformer

In [92]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [94]:
transformer.fit_transform(X_train).shape

(80, 7)

In [98]:
transformer.transform(X_test).shape

(20, 7)